### ISSUE TITLE
Rules not properly using threads

### ISSUE THREAD

**Issue by dominikburri** [zavolanlab/PAQR2#14]
When running 4 samples I noticed that the load average increased to ~32, and many python threads are spawned (very likely 32), but I supplied only 12 threads for the execution. This indicates a bug. 

Snakemake can only handle the use of multiple cores/threads correctly if it is supplied as *threads* keyword, see [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#threads).

This is not the case for
* https://github.com/zavolanlab/PAQR2/blob/9cab5bc78dd3523d28f2efdba1e4ee73155f4831/Snakefile#L130
* https://github.com/zavolanlab/PAQR2/blob/9cab5bc78dd3523d28f2efdba1e4ee73155f4831/Snakefile#L230

which are within *params*. These parameters should be moved to a new directive like:
```
threads: 8 
```

and then referenced with `{threads}` in the *shell* command.

This would ensure that snakemake can correctly schedule the workflow.

**Comment by AngryMaciek** [comment]
@dominikburri you are right, my mistake.  
Feel free to start a PR with a fix and I will approve :)
